services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: astrup_prod

  web:
    build: .
    ports:
      - 4001:4000
    depends_on:
      - db
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/astrup_prod
      SECRET_KEY_BASE: i/6iktt1vYiWLJTo7qqmiBvk7dcWpghLZXqlyFG876dxLz2OyXXSCDwKEN5GG4Fw
      PHX_HOST: localhost
